import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class SMA_GUI extends javax.swing.JFrame {

	protected Salle salle;
	private Boolean STOP = true;

	/**
	 * Creates new form SMAGUI
	 */
	public SMA_GUI() {
		initComponents();
		this.salle = new Salle(70, (Integer) lightSpinner.getValue(),
				(Integer) shutterSpinner.getValue(), 1);
	}

	public void refresh() {
		initComponents();
		salle.update();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		startButton = new javax.swing.JButton();
		lightSpinner = new javax.swing.JSpinner();
		jLabel1 = new javax.swing.JLabel();
		shutterSpinner = new javax.swing.JSpinner();
		jLabel2 = new javax.swing.JLabel();
		satisfactionSlider = new javax.swing.JSlider();
		jLabel3 = new javax.swing.JLabel();
		stopButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		brightnessTextPane = new javax.swing.JTextPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		energyTextPane = new javax.swing.JTextPane();
		jSeparator1 = new javax.swing.JSeparator();
		graphButton = new javax.swing.JButton();
		timeLabel = new javax.swing.JLabel();

		BufferedImage lightImage = null;
		try {
			lightImage = ImageIO.read(new File("light.png"));
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		if (lightImage != null) {
			light1Label = new JLabel(new ImageIcon(lightImage));
			light2Label = new JLabel(new ImageIcon(lightImage));
			light3Label = new JLabel(new ImageIcon(lightImage));
			light4Label = new JLabel(new ImageIcon(lightImage));
			light5Label = new JLabel(new ImageIcon(lightImage));
		} else {
			light1Label = new javax.swing.JLabel();
			light2Label = new javax.swing.JLabel();
			light3Label = new javax.swing.JLabel();
			light4Label = new javax.swing.JLabel();
			light5Label = new javax.swing.JLabel();
			light1Label.setText("light1");
			light2Label.setText("light2");
			light3Label.setText("light3");
			light4Label.setText("light4");
			light5Label.setText("light5");
		}
		BufferedImage sunImage = null;
		try {
			sunImage = ImageIO.read(new File("sun.png"));
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		if (sunImage != null) {
			sunLabel = new JLabel(new ImageIcon(sunImage));
		} else {
			sunLabel = new javax.swing.JLabel();
			sunLabel.setText("Sun");
		}

		BufferedImage shutterImage = null;
		try {
			shutterImage = ImageIO.read(new File("shutter.png"));
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		if (shutterImage != null) {
			shutter1Label = new JLabel(new ImageIcon(shutterImage));
			shutter2Label = new JLabel(new ImageIcon(shutterImage));
		} else {
			shutter1Label = new javax.swing.JLabel();
			shutter2Label = new javax.swing.JLabel();
			shutter1Label.setText("Shutter1");
			shutter2Label.setText("Shutter2");
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		startButton.setText("Tick");
		startButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stopButton.setEnabled(true);
				lightSpinner.setEnabled(false);
				shutterSpinner.setEnabled(false);
				STOP = false;
				System.out.println("TICK");
				salle.setSatisfaction((Integer) satisfactionSlider.getValue());
				runProg();
			}
		});

		stopButton.setText("Stop");
		stopButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stopButton.setEnabled(false);
				graphButton.setEnabled(true);
				lightSpinner.setEnabled(true);
				shutterSpinner.setEnabled(true);
				STOP = true;
				System.out.println("STOP");
			}
		});

		if (STOP) {
			startButton.setEnabled(true);
			stopButton.setEnabled(false);
			lightSpinner.setEnabled(true);
			shutterSpinner.setEnabled(true);
			graphButton.setEnabled(false);
		} else {
			startButton.setEnabled(false);
			stopButton.setEnabled(true);
			lightSpinner.setEnabled(false);
			shutterSpinner.setEnabled(false);
			graphButton.setEnabled(true);
		}

		lightSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
		lightSpinner.setToolTipText("number of lights");

		jLabel1.setText("Number of Lights");

		shutterSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 0, 2, 1));
		shutterSpinner.setToolTipText("number of lights");

		jLabel2.setText("Number of Shutters");

		satisfactionSlider.setValue(100);

		jLabel3.setText("Satisfaction");

		brightnessTextPane.setText("Brightness:");
		jScrollPane1.setViewportView(brightnessTextPane);

		energyTextPane.setText("Energy used:");
		jScrollPane2.setViewportView(energyTextPane);

		graphButton.setText("Build Graphs");
		graphButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					Process p = Runtime.getRuntime().exec("python graph.py");
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});

		timeLabel.setText("Time: ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										light1Label)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										light2Label)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		light3Label)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		light4Label)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		light5Label))
																												.addComponent(
																														sunLabel))
																								.addGap(0,
																										3,
																										Short.MAX_VALUE))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addGap(0,
																										0,
																										Short.MAX_VALUE)
																								.addComponent(
																										shutter1Label)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														shutterSpinner,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														lightSpinner,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		jLabel1,
																																		javax.swing.GroupLayout.Alignment.TRAILING)
																																.addComponent(
																																		jLabel2,
																																		javax.swing.GroupLayout.Alignment.TRAILING))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		startButton)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		stopButton))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jSeparator1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addComponent(
																														satisfactionSlider,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														0,
																														Short.MAX_VALUE)
																												.addComponent(
																														jScrollPane1)
																												.addComponent(
																														jScrollPane2,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														121,
																														Short.MAX_VALUE)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(28,
																																		28,
																																		28)
																																.addComponent(
																																		jLabel3))))))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		timeLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		graphButton)))
								.addContainerGap())
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addGap(22, 22, 22)
												.addComponent(shutter2Label)
												.addContainerGap(330,
														Short.MAX_VALUE))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		startButton)
																.addComponent(
																		stopButton))
												.addComponent(
														sunLabel,
														javax.swing.GroupLayout.Alignment.LEADING))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lightSpinner,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(light1Label)
												.addComponent(light2Label)
												.addComponent(light3Label)
												.addComponent(light4Label)
												.addComponent(light5Label))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						shutterSpinner,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jSeparator1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						10,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										satisfactionSlider,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jScrollPane2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						shutter1Label))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		graphButton))
												.addComponent(
														timeLabel,
														javax.swing.GroupLayout.Alignment.TRAILING))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addGap(149, 149, 149)
												.addComponent(shutter2Label)
												.addContainerGap(161,
														Short.MAX_VALUE))));

		pack();
	}// </editor-fold>

	public void runProg() {
		light1Label.setVisible(false);
		light2Label.setVisible(false);
		light3Label.setVisible(false);
		light4Label.setVisible(false);
		light5Label.setVisible(false);
		shutter1Label.setVisible(false);
		shutter2Label.setVisible(false);
		if (salle.getSun() > 0) {
			sunLabel.setVisible(true);
		} else {
			sunLabel.setVisible(false);
		}
		ArrayList<JLabel> lights = new ArrayList<JLabel>();
		lights.add(light1Label);
		lights.add(light2Label);
		lights.add(light3Label);
		lights.add(light4Label);
		lights.add(light5Label);

		ArrayList<JLabel> shutters = new ArrayList<JLabel>();

		if (!STOP) {
			shutters.add(shutter1Label);
			shutters.add(shutter2Label);
			for (int i = 0; i < (Integer) shutterSpinner.getValue(); i++) {
				shutters.get(i).setVisible(true);
			}
			for (int i = 0; i < (Integer) lightSpinner.getValue(); i++) {
				lights.get(i).setVisible(true);
			}
			salle.update();
			salle.setSatisfaction((Integer) satisfactionSlider.getValue());
			brightnessTextPane.setText("Brightness:\t" + salle.getLuminosite()
					+ "%\n");
			energyTextPane.setText("Energy used:\t" + salle.getNrj()
					+ " watts\n");
			timeLabel.setText("Time: " + salle.getTime() + "\n");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SMA_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SMA_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SMA_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SMA_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				SMA_GUI sg = new SMA_GUI();
				sg.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton startButton;
	private javax.swing.JButton stopButton;
	private javax.swing.JButton graphButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel sunLabel;
	private javax.swing.JLabel shutter1Label;
	private javax.swing.JLabel shutter2Label;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel timeLabel;
	private javax.swing.JLabel light1Label;
	private javax.swing.JLabel light2Label;
	private javax.swing.JLabel light3Label;
	private javax.swing.JLabel light4Label;
	private javax.swing.JLabel light5Label;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSlider satisfactionSlider;
	private javax.swing.JSpinner lightSpinner;
	private javax.swing.JSpinner shutterSpinner;
	private javax.swing.JTextPane brightnessTextPane;
	private javax.swing.JTextPane energyTextPane;
	// End of variables declaration
}
